// ─── TTS Provider Interface ─────────────────────────────────
// Provider-agnostic types for text-to-speech synthesis.
// Add new providers by implementing TTSProvider.

export type TTSRequest = {
  text: string;
  voiceId: string;
  format?: "mp3" | "wav" | "opus";
  speed?: number;
  /** Provider-specific emotion/style tags */
  emotion?: string | null;
};

export type TTSResult = {
  audioBuffer: Buffer;
  durationSeconds: number;
};

export interface TTSProvider {
  readonly name: string;
  synthesize(request: TTSRequest): Promise<TTSResult>;
  cloneVoice?(audioFilePath: string, name: string): Promise<string>;
}

// ─── Manifest Types ─────────────────────────────────────────
// Structured scene data output by /video Phase 3.
// Narration planning fields (narrationIntent, onScreenText, narratorTone)
// are optional for backward compatibility with older manifests.

export type SceneManifest = {
  sceneIndex: number;
  sceneType: string;
  durationSeconds: number;
  transitionAfter?: { type: string; frames: number };
  props: Record<string, unknown>;
  /** Creative directive for the transcript writer (what the narration should accomplish) */
  narrationIntent?: string;
  /** Text strings visible on screen (narrator avoids reading these verbatim) */
  onScreenText?: string[];
  /** Emotional guidance for this specific scene */
  narratorTone?: string;
};

export type SectionManifest = {
  sectionIndex: number;
  title: string;
  durationFrames: number;
  scenes: SceneManifest[];
  /** Hex color from SECTION_THEMES */
  sectionColor?: string;
  /** Overall emotional arc for the section */
  sectionTone?: string;
  /** Which scene index (within section) carries the humor beat */
  humorScene?: number;
};

export type VideoManifest = {
  videoName: string;
  fps: number;
  totalFrames: number;
  meta?: {
    learningObjectives?: string[];
    audienceProfile?: string;
    humorStyle?: string;
  };
  sections: SectionManifest[];
};

// ─── Transcript Types ───────────────────────────────────────
// Generated by Phase 4, consumed by TTS synthesis.

export type SceneTranscript = {
  sceneIndex: number;
  sectionIndex: number;
  sceneType: string;
  durationSeconds: number;
  /** Effective duration after subtracting transition overlap */
  effectiveDurationSeconds: number;
  /** Transition frames shared with the next scene (0 if last in section) */
  transitionAfterFrames: number;
  wordBudget: number;
  onScreenText: string[];
  /** Creative directive from /video scene planning (passed through from manifest) */
  narrationIntent?: string;
  /** Emotional guidance for this scene (passed through from manifest) */
  narratorTone?: string;
  narration: string;
  /** Populated after TTS synthesis */
  audioFile?: string;
  actualDurationSeconds?: number;
};

export type Transcript = {
  videoName: string;
  voiceId: string;
  scenes: SceneTranscript[];
};

// ─── Voiceover Scene (for Remotion) ─────────────────────────
// Used by VoiceoverLayer component.

export type VoiceoverScene = {
  src: string;
  fromFrame: number;
  durationInFrames: number;
};
